# POST http://localhost:3000/create HTTP/1.1
# Content-Type: application/json

# {
#     "name": "小刘",
#     "email": "1402098743@qq.com"
# }




# POST http://localhost:3000/update HTTP/1.1
# Content-Type: application/json

# {
#     "name": "小刘2",
#     "email": "140@qq.com",
#     "id": 1
# }





# POST http://localhost:3000/delete HTTP/1.1
# Content-Type: application/json

# {
#     "id": 1
# }




GET http://localhost:3000/user/index HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsIm5hbWUiOiJhc2Rhc2QiLCJlbWFpbCI6ImR3cWRxQHFkcS5jb20iLCJpYXQiOjE3MjczNzkwOTUsImV4cCI6MTcyNzk4Mzg5NX0.d6zyLn2AwGY6Ab1aaIIdNFS5F6O0RrfBwmN2RET-WBU


# POST http://localhost:3000/user/create HTTP/1.1
# Content-Type: application/json

# {
#     "name": "asdasd",
#     "email": "dwqdq@qdq.com"
# }

